# Generated by Django 2.1.15 on 2022-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='BusinessCategory',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Datails',
        ),
        migrations.AddField(
            model_name='business',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='BusinessEmail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='BusinessNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='LegalEntityName',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='business',
            name='businessIndustry',
        ),
        migrations.AddField(
            model_name='business',
            name='businessIndustry',
            field=models.ManyToManyField(to='UserStoryApp.BusinessCategory'),
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
    ]
