# Generated by Django 2.1.15 on 2022-11-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0004_userstoryversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='US_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStoryApp.US_Group'),
        ),
    ]
