# Generated by Django 4.1.3 on 2022-12-07 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0006_business_user_project_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='userStoriesVersion',
        ),
        migrations.AddField(
            model_name='userstory',
            name='userStoriesVersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStoryApp.userstoryversion'),
        ),
    ]
