# Generated by Django 4.1.3 on 2022-12-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0007_remove_userstory_userstoriesversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
