# Generated by Django 4.1.3 on 2022-12-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0008_remove_epic_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='User',
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
