# Generated by Django 4.1.3 on 2022-12-09 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0009_remove_business_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
