# Generated by Django 4.1.3 on 2022-12-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0010_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ABN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
