# Generated by Django 4.1.3 on 2022-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0011_business_abn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimates',
            name='UserStory',
        ),
        migrations.AddField(
            model_name='userstory',
            name='Estimates',
            field=models.ManyToManyField(to='UserStoryApp.estimates'),
        ),
    ]
