# Generated by Django 4.1.3 on 2022-12-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0012_remove_estimates_userstory_userstory_estimates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='Platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserStoryApp.platform'),
        ),
    ]
