# Generated by Django 4.1.3 on 2023-01-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0013_alter_estimates_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
