# Generated by Django 4.1.3 on 2023-01-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0014_remove_project_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='Epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStoryApp.epic'),
        ),
    ]
