# Generated by Django 4.1.3 on 2023-01-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryApp', '0015_alter_userstory_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstoryversion',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStoryApp.project'),
        ),
    ]
